In [149]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.datasets import load_digits

In [150]:
digits= load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [151]:
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2)

In [152]:
lr= LogisticRegression(max_iter=100000)
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.9611111111111111

In [153]:
svm= SVC(C=10, kernel='rbf', gamma=0.001)
svm.fit(x_train, y_train)
svm.score(x_test, y_test) 

0.9861111111111112

In [154]:
rf= RandomForestClassifier(n_estimators=100)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9694444444444444

In [155]:
from sklearn.model_selection import KFold
kf= KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [156]:
for train_index, test_index in kf.split([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print("Train:", train_index, "Test:", test_index)

Train: [4 5 6 7 8 9] Test: [0 1 2 3]
Train: [0 1 2 3 7 8 9] Test: [4 5 6]
Train: [0 1 2 3 4 5 6] Test: [7 8 9]


In [157]:
def get_score(model, x_train, y_train, x_test, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [158]:
get_score(lr, x_train, y_train, x_test, y_test)
get_score(svm, x_train, y_train, x_test, y_test)
get_score(rf, x_train, y_train, x_test, y_test)

0.9805555555555555

In [159]:
from sklearn.model_selection import StratifiedKFold
folds= StratifiedKFold(n_splits=3)

In [160]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    x_train, x_test = digits.data[train_index], digits.data[test_index]
    y_train, y_test = digits.target[train_index], digits.target[test_index]
    scores_lr.append(get_score(lr, x_train, y_train, x_test, y_test))
    scores_svm.append(get_score(svm, x_train, y_train, x_test, y_test))
    scores_rf.append(get_score(rf, x_train, y_train, x_test, y_test))
print("Logistic Regression scores:", scores_lr)
print("SVM scores:", scores_svm)
print("Random Forest scores:", scores_rf)

Logistic Regression scores: [0.9248747913188647, 0.9432387312186978, 0.9148580968280468]
SVM scores: [0.9716193656093489, 0.9816360601001669, 0.9682804674457429]
Random Forest scores: [0.9382303839732888, 0.9565943238731218, 0.9181969949916527]


In [161]:
from sklearn.model_selection import cross_val_score


In [162]:
cross_val_score(lr, digits.data, digits.target, cv=3)

array([0.91986644, 0.94156928, 0.91652755])

In [163]:
cross_val_score(svm, digits.data, digits.target, cv=3)

array([0.97161937, 0.98163606, 0.97495826])

In [164]:
cross_val_score(rf, digits.data, digits.target, cv=3)

array([0.93823038, 0.95158598, 0.93155259])

In [165]:
from sklearn.datasets import load_iris
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [166]:
cross_val_score(LogisticRegression(max_iter=120), iris.data, iris.target, cv=3)

array([0.98, 0.96, 0.98])

In [167]:
cross_val_score(SVC(), digits.data, digits.target, cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [172]:
cross_val_score(DecisionTreeClassifier(), digits.data, digits.target, cv=3)

array([0.73789649, 0.83639399, 0.77963272])

In [183]:
cross_val_score(RandomForestClassifier(n_estimators=70), digits.data, digits.target, cv=3)

array([0.93656093, 0.95826377, 0.92320534])