In [99]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.model_selection import cross_val_score, GridSearchCV, RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [68]:
iris = load_iris()

In [69]:
df= pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['flower']= iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df[47:150]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),flower
47,4.6,3.2,1.4,0.2,setosa
48,5.3,3.7,1.5,0.2,setosa
49,5.0,3.3,1.4,0.2,setosa
50,7.0,3.2,4.7,1.4,versicolor
51,6.4,3.2,4.5,1.5,versicolor
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica


In [70]:
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3)
model_svm = svm.SVC(kernel='rbf', C=1.0, gamma='auto')


In [71]:
model_svm.fit(x_train, y_train)
model_svm.score(x_test, y_test)

0.9333333333333333

In [72]:
cross_val_score(svm.SVC(kernel='linear',C=10,gamma='auto'), iris.data, iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [73]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [74]:
cross_val_score(svm.SVC(kernel='linear',C=20,gamma='auto'), iris.data, iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

In [75]:
kernel = ['linear', 'rbf']
C = [1, 10, 20]
avg_scores = []
for k in kernel:
    for cval in C:
      cv_scores = cross_val_score(svm.SVC(kernel=k, C=cval, gamma='auto'), iris.data, iris.target, cv=5)
      avg_scores.append((k, cval, np.mean(cv_scores)))

avg_scores

[('linear', 1, np.float64(0.9800000000000001)),
 ('linear', 10, np.float64(0.9733333333333334)),
 ('linear', 20, np.float64(0.9666666666666666)),
 ('rbf', 1, np.float64(0.9800000000000001)),
 ('rbf', 10, np.float64(0.9800000000000001)),
 ('rbf', 20, np.float64(0.9666666666666668))]

In [76]:
clf= GridSearchCV(svm.SVC(gamma='auto'), {'C': [1, 10, 20], 'kernel': ['rbf', 'linear']}, cv=5, return_train_score=False)

clf.fit(iris.data, iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00137744, 0.00080328, 0.00076065, 0.00069003, 0.00073786,
        0.00070219]),
 'std_fit_time': array([2.47365801e-04, 9.15330379e-05, 3.34733572e-05, 5.99717091e-05,
        3.34858534e-05, 6.08139201e-05]),
 'mean_score_time': array([0.00085239, 0.00073838, 0.00060186, 0.00050759, 0.00064259,
        0.00052409]),
 'std_score_time': array([1.41161389e-04, 1.79382057e-04, 7.07733976e-05, 1.63430675e-05,
        1.24014097e-04, 5.58395247e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
 

In [77]:
df1 = pd.DataFrame(clf.cv_results_)
df1

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001377,0.000247,0.000852,0.000141,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.000803,0.000092,0.000738,0.000179,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.000761,0.000033,0.000602,0.000071,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.000690,0.000060,0.000508,0.000016,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.000738,0.000033,0.000643,0.000124,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.000702,0.000061,0.000524,0.000056,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6


In [78]:
df1[['param_C', 'param_kernel', 'mean_test_score', 'rank_test_score']]

,param_C,param_kernel,mean_test_score,rank_test_score
0,1,rbf,0.980000,1
1,1,linear,0.980000,1
2,10,rbf,0.980000,1
3,10,linear,0.973333,4
4,20,rbf,0.966667,5
5,20,linear,0.966667,6


In [79]:
dir(clf)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_routed_params_for_fit',
 '_get_scorers',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr

In [80]:
clf.best_score_

np.float64(0.9800000000000001)

In [81]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [82]:
rs= RandomizedSearchCV(svm.SVC(gamma='auto'), {'C': [1, 10, 20], 'kernel': ['rbf', 'linear']}, cv=5, n_iter=2, return_train_score=False)

In [83]:
rs.fit(iris.data, iris.target)
pd.DataFrame(rs.cv_results_)[['param_C', 'param_kernel', 'mean_test_score', 'rank_test_score']]

,param_C,param_kernel,mean_test_score,rank_test_score
0,1,linear,0.980000,1
1,20,linear,0.966667,2


In [92]:
model_param = {'svm' :{ 'model': svm.SVC(gamma='auto'), 
               'params': {'C': [1, 10, 20], 'kernel': ['rbf', 'linear']}},
               'random_forest': {'model': RandomForestClassifier(),
               'params': {'n_estimators': [1, 5, 10]}},
               'logistic_regression': {'model' : LogisticRegression(solver='liblinear', multi_class='auto'),
                'params': {'C': [1, 5, 10]}}}
               
               

In [94]:
scores = []
for model_name, mp in model_param.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({'model': model_name, 'best_score': clf.best_score_, 'best_params': clf.best_params_})
scores

c:\Users\Niloy\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\Niloy\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\Niloy\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\Niloy\AppData\Local\Programs\Python\P

[{'model': 'svm',
  'best_score': np.float64(0.9800000000000001),
  'best_params': {'C': 1, 'kernel': 'rbf'}},
 {'model': 'random_forest',
  'best_score': np.float64(0.9533333333333334),
  'best_params': {'n_estimators': 5}},
 {'model': 'logistic_regression',
  'best_score': np.float64(0.9666666666666668),
  'best_params': {'C': 5}}]

In [97]:
df2= pd.DataFrame(scores)
df2

,model,best_score,best_params
0,svm,0.980000,"{'C': 1, 'kernel': 'rbf'}"
1,random_forest,0.953333,{'n_estimators': 5}
2,logistic_regression,0.966667,{'C': 5}


In [100]:
from sklearn.datasets import load_digits
digits = load_digits()

In [106]:
model_params = { 'svm': {'model': svm.SVC(gamma='auto'),
                'params': {'C': [1, 10, 20], 'kernel': ['rbf', 'linear']}},
                'random_forest': {'model': RandomForestClassifier(),
                'params': {'n_estimators': [1, 5, 10]}},
                'Logistic_Regression': {'model': LogisticRegression(solver='liblinear', multi_class='auto'),
                'params' : {"C": [1, 5, 10]}},
                'Decision_Tree': {'model': DecisionTreeClassifier(),
                'params': {'criterion': ['gini', 'entropy']}},
                'Gaussian_NB': {'model': GaussianNB(),
                'params': {}},
                'Multinomial_NB': {'model': MultinomialNB(),
                'params': {}},
                'Bernoulli_NB': {'model': BernoulliNB(),
                'params': {}}}

In [113]:
scoress= []
for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(digits.data, digits.target)
    scoress.append({'model': model_name, 'best_score': clf.best_score_, 'best_params': clf.best_params_})
pd.DataFrame(scoress)

c:\Users\Niloy\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\Niloy\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\Niloy\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\Niloy\AppData\Local\Programs\Python\P

,model,best_score,best_params
0,svm,0.947697,"{'C': 1, 'kernel': 'linear'}"
1,random_forest,0.904314,{'n_estimators': 10}
2,Logistic_Regression,0.922114,{'C': 1}
3,Decision_Tree,0.809158,{'criterion': 'entropy'}
4,Gaussian_NB,0.806928,{}
5,Multinomial_NB,0.870350,{}
6,Bernoulli_NB,0.824174,{}
